### ISSUE TITLE
Please provide version 0.19 packages for ubuntu 14.04 trusty

### ISSUE THREAD

**Issue by dannyman** [grnet/snf-image#87]
Nikos,

Thank you for your presentation at Ganeticon. This is followup from a question I posed about support for 16.04 images. I think our challenges may be rooted in running an older version (0.18). Would it be fairly easy for you to build 0.19 packages for the apt repo?

http://apt.dev.grnet.gr/trusty/

Thanks,
-danny

**Comment by skalkoto** [comment]
Oh sorry! I'll upload trusty packages to the repo on Monday. You are probably referring to this:
* Support Ed24419 ssh keys
that was fixed in version 0.19
https://github.com/grnet/snf-image/blob/develop/ChangeLog

**Comment by skalkoto** [comment]
snf-image v0.19.1 for trusty is in the repo.
