### ISSUE TITLE
Consider modifying /etc/mailname upon instance creation

### ISSUE THREAD

**Issue by irregulator** [grnet/snf-image#96]
Hi,

We've been using snf-image '0.20.2-1~jessie' on jessie hosts. Currently it seems that upon instance creation '/etc/mailname' is simply copied from the original image. The string in that configuration file is used when sending or relaying email and can lead to mail delivery failure if not properly set.

I think it would be better if snf-image would set '/etc/mailname' to contain the host's fqdn. I imagine this needs a task similar to "50AssignHostname" or a modification to it.

Thanks for developing snf-image

**Comment by skalkoto** [comment]
Maybe simply just do this inside AssignHostname task? I mean this is part of assigning the hostname isn't it? The only problem I see is that the hostname is assigned by just using the VM name. If this name is not a FQDN, I don't think there is a way to find it out.
