### ISSUE TITLE
qemu_nbd -d cleanup does not run

### ISSUE THREAD

**Issue by skalkoto** [grnet/snf-image#99]
```
for ((i=0; i<max; i++)); do                                                 
        set +e                                                                  
        $QEMU_NBD -c "/dev/nbd$i" "$disk"                                       
        rc=$?                                                                   
        set -e                                                                  
        if [ $rc -eq 0 ]; then                                                  
            add_cleanup $QEMU_NBD -d "/dev/nbd$i"                               
            break                                                               
        else                                                                    
            log_warning "Unable to map \`$disk' to /dev/nbd$i"                  
        fi                                                                      
    done
```
This piece of code will connect to an ndb device and then register the disconnection to be done at cleanup. The problem is that this is called in a subshell environment like this: ``disk=$(find_disk 0)`` which means that the ``add_cleanup`` function will not register the cleanup command to the original ``CLEANUP`` array but to the one of the subshell hence the command is never called. The same goes for the ``losetup_disk`` command.

**Comment by kasimon** [comment]
Just a small recommendation, in case you don't know it (like I a few weeks ago): Problems of this kind can often be found by the awesome 'shellcheck' tool. https://www.shellcheck.net/

**Comment by skalkoto** [comment]
Thank you for the info. I'll check it.
